#!/bin/bash --login
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=1:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=5G
#SBATCH --partition=k2-epsrc
module purge;
module load compilers/gcc/9.3.0;
module load mpi/openmpi/4.1.1/gcc-9.3.0;
module load libs/atlas/3.10.3/gcc-9.3.0;
module load apps/cmake/3.25.1/gcc-9.3.0;
module load apps/python3/3.10.5/gcc-9.3.0;
source /users/asmith/programs/kelvenv/bin/activate 
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/users/asmith/programs/lammps/build/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/users/asmith/programs/lammps/src/
echo $LD_LIBRARY_PATH
python3 run_anneal.py
#srun /users/asmith/programs/lammps/build/lmp -in /users/asmith/grun_out/anneal_output/20240306190529/anneal1500K_silica.lammps_ctrl