#!/bin/bash --login
#SBATCH --nodes=1
#SBATCH --ntasks=60
#SBATCH --time=48:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=5G
#SBATCH --partition=k2-epsrc-himem
module purge;
module load compilers/gcc/9.3.0;
module load mpi/openmpi/4.1.1/gcc-9.3.0;
module load libs/atlas/3.10.3/gcc-9.3.0;
module load apps/cmake/3.25.1/gcc-9.3.0;
module load apps/python3/3.10.5/gcc-9.3.0;
source /users/asmith/programs/kelvenv/bin/activate 
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export NTASKS=$SLURM_NTASKS 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/userapps/q13camb_apps/lammps/build/
echo $LD_LIBRARY_PATH

echo "start neighbour calculations"
python3 calc_NL.py > neighbour_work.out
echo "start forces calculation"
mpirun -np $SLURM_NTASKS python3 RAP2_sparse.py > rap2_work.out
echo "start collection"
python3 collect_RAP2_sparse.py > collect_work.out
echo "start conversion"
python3 sparse_spRAP_convert.py
echo "done"