#!/bin/bash --login

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=100G

#SBATCH --partition=k2-epsrc-himem
now=$(date)
echo "start time : $now"

source setup_script
module load libs/openblas/0.3.20/gcc-9.3.0
module load services/s3cmd


echo "##########################################################"
echo "Number of tasks:" $SLURM_NTASKS
echo "Number of OMP_NUM_THREADS:" $SLURM_CPUS_PER_TASK
echo "List of machines:" $SLURM_NODELIST
echo "Current folder:" `pwd`
echo "##########################################################"
echo "Job started: " `date`

mkdir 4_fc3
cp relaxed_model/POSCAR 4_fc3

cd 4_fc3
python3 "$AMORPHO_PATH/rap3/calc_NL_compList.py" > nl3_out.out


now=$(date)
echo "end time : $now"