#!/bin/bash
#SBATCH --time=0-01:30:00
#SBATCH --job-name=grun
#####SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --mem-per-cpu 50G
####SBATCH --cpus-per-task=96
#SBATCH --partition=k2-epsrc-himem
now=$(date)
echo "start time : $now"
source setup_script

python3 "$AMORPHO_PATH/prepare.py" GRUNEISEN

cd "5_gruneisen"
"$AMORPHO_PATH/bin/gruneisen/int_strain.exe" > grunint_out.out
echo "did pre-calculation for IS"
sed -i "1s/.*/IS/" inputs
mpirun "$AMORPHO_PATH/bin/gruneisen/grun_mpi.exe" > grungrun2_IS.out    ## to calculate rmean-part
echo "did IS"
sed -i "1s/.*/MAIN/" inputs
mpirun "$AMORPHO_PATH/bin/gruneisen/grun_mpi.exe" > grungrun2_MAIN.out    ## to calculate rmean-part
echo "did MAIN"

cd ..
now=$(date)
echo "end time : $now"