#!/bin/bash --login

#SBATCH --nodes=1
#SBATCH --ntasks=128
#SBATCH --time=48:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=5G

#SBATCH --partition=k2-epsrc-himem

now=$(date)
echo "start time : $now"
source setup_script
module load services/s3cmd
module load libs/openblas/0.3.20/gcc-9.3.0

echo "##########################################################"
echo "Number of tasks:" $SLURM_NTASKS
echo "Number of OMP_NUM_THREADS:" $SLURM_CPUS_PER_TASK
echo "List of machines:" $SLURM_NODELIST
echo "Current folder:" `pwd`
echo "##########################################################"
echo "Job started: " `date`

cd 4_fc3
mpirun -np $SLURM_NTASKS python3 "$AMORPHO_PATH/rap3/RAP_fc3_compList.py" > fc3_out.out
python3 "$AMORPHO_PATH/rap3/collect_RAP3.py" > collect_out.out

now=$(date)
echo "end time : $now"