#!/bin/bash --login
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=48:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=6G
#SBATCH --partition=k2-epsrc-himem
now=$(date)
echo "start time : $now"
source setup_script
mkdir 3_diagonalise_python
python3 "$AMORPHO_PATH/diagonalise_python/py_diag.py" > diag_work.out
cd 3_diagonalise_python
python3 "$AMORPHO_PATH/diagonalise_python/convert_freq.py" > convert_work.out
cd ..

mkdir 3_diagonalise
cp -a 3_diagonalise_python/. 3_diagonalise/

now=$(date)
echo "end time : $now"