#!/bin/bash --login
#SBATCH --job-name=vgrun2
#SBATCH --nodes=1
#SBATCH --ntasks=60
#SBATCH --time=48:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=5G
#SBATCH --partition=k2-epsrc-himem
now=$(date)
echo "start time : $now"
source setup_script

python3 "$AMORPHO_PATH/numeric_gruneisen/do_fc2.py"

now=$(date)
echo "end time : $now"