#!/bin/bash --login
#SBATCH --job-name=vgrun3
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=48:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=10G
#SBATCH --partition=k2-epsrc-himem
now=$(date)
echo "start time : $now"
source setup_script

python3 "$AMORPHO_PATH/numeric_gruneisen/diagonalise_all.py"

now=$(date)
echo "end time : $now"