#!/bin/bash --login
#SBATCH --job-name=vgrun1
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH --time=48:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G
#SBATCH --partition=k2-epsrc-himem
now=$(date)
echo "start time : $now"
source setup_script

python3 "$AMORPHO_PATH/numeric_gruneisen/numeric_gruneisen.py"

now=$(date)
echo "end time : $now"