#!/bin/bash --login

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --mail-type=NONE
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=100G

#SBATCH --partition=k2-epsrc

conda deactivate
module purge
module load services/s3cmd
module load compilers/gcc/9.3.0
module load apps/cmake/3.25.1/gcc-9.3.0
module load mpi/openmpi/4.1.1/gcc-9.3.0
module load libs/openblas/0.3.20/gcc-9.3.0
module load apps/python3/3.10.5/gcc-9.3.0


echo "##########################################################"
echo "Number of tasks:" $SLURM_NTASKS
echo "Number of OMP_NUM_THREADS:" $SLURM_CPUS_PER_TASK
echo "List of machines:" $SLURM_NODELIST
echo "Current folder:" `pwd`
echo "##########################################################"
echo "Job started: " `date`


source /users/asmith/programs/kelvenv/bin/activate 
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export NTASKS=$SLURM_NTASKS 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/userapps/q13camb_apps/lammps/build/
echo $LD_LIBRARY_PATH
python3 calc_NL_compList.py > nl3_out.out


echo "Job finished: " `date`